// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestAccountCreationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testAccountCreation() {
    // Test name: TestAccountCreation
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://rentacpap.co/");
    // 2 | setWindowSize | 1575x860 | 
    driver.manage().window().setSize(new Dimension(1575, 860));
    // 3 | click | linkText=Log In | 
    driver.findElement(By.linkText("Log In")).click();
    // 4 | mouseOver | linkText=Log In | 
    {
      WebElement element = driver.findElement(By.linkText("Log In"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | mouseOut | linkText=Log In | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | click | linkText=Create an Account | 
    driver.findElement(By.linkText("Create an Account")).click();
    // 7 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 8 | type | name=email | EasyB_QA1@fromthemind.com
    driver.findElement(By.name("email")).sendKeys("EasyB_QA1@fromthemind.com");
    // 9 | click | css=.container | 
    driver.findElement(By.cssSelector(".container")).click();
    // 10 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 11 | type | name=password | E4syBr34th3
    driver.findElement(By.name("password")).sendKeys("E4syBr34th3");
    // 12 | type | name=password2 | E4syBr34th3
    driver.findElement(By.name("password2")).sendKeys("E4syBr34th3");
    // 13 | click | css=.ex-customers > input:nth-child(4) | 
    driver.findElement(By.cssSelector(".ex-customers > input:nth-child(4)")).click();
    // 14 | click | name=shipFName | 
    driver.findElement(By.name("shipFName")).click();
    // 15 | type | name=shipFName | EasyB1
    driver.findElement(By.name("shipFName")).sendKeys("EasyB1");
    // 16 | click | css=.address:nth-child(10) div:nth-child(2) > label | 
    driver.findElement(By.cssSelector(".address:nth-child(10) div:nth-child(2) > label")).click();
    // 17 | click | name=shipLName | 
    driver.findElement(By.name("shipLName")).click();
    // 18 | type | name=shipLName | QA_1
    driver.findElement(By.name("shipLName")).sendKeys("QA_1");
    // 19 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 20 | click | name=shipAddress1 | 
    driver.findElement(By.name("shipAddress1")).click();
    // 21 | type | name=shipAddress1 | 1234 5th St
    driver.findElement(By.name("shipAddress1")).sendKeys("1234 5th St");
    // 22 | click | css=.address:nth-child(10) div:nth-child(6) > label | 
    driver.findElement(By.cssSelector(".address:nth-child(10) div:nth-child(6) > label")).click();
    // 23 | click | name=shipCity | 
    driver.findElement(By.name("shipCity")).click();
    // 24 | type | name=shipEmail | EasyB_QARX@fromthemind.com
    driver.findElement(By.name("shipEmail")).sendKeys("EasyB_QARX@fromthemind.com");
    // 25 | type | name=shipCity | Schenectady
    driver.findElement(By.name("shipCity")).sendKeys("Schenectady");
    // 26 | select | name=usState1 | label=NY - New York
    {
      WebElement dropdown = driver.findElement(By.name("usState1"));
      dropdown.findElement(By.xpath("//option[. = 'NY - New York']")).click();
    }
    // 27 | type | name=shipZip | 12345
    driver.findElement(By.name("shipZip")).sendKeys("12345");
    // 28 | click | css=.address:nth-child(10) .c | 
    driver.findElement(By.cssSelector(".address:nth-child(10) .c")).click();
  }
}
