// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test8CustomerFromTest7SmallItemsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test8CustomerFromTest7SmallItems() {
    // Test name: Test8 CustomerFromTest7SmallItems
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://rentacpap.co/");
    // 2 | setWindowSize | 1575x860 | 
    driver.manage().window().setSize(new Dimension(1575, 860));
    // 3 | click | linkText=Log In | 
    driver.findElement(By.linkText("Log In")).click();
    // 4 | click | name=cEmail1 | 
    driver.findElement(By.name("cEmail1")).click();
    // 5 | type | name=cEmail1 | ecart2@rentacpap.co
    driver.findElement(By.name("cEmail1")).sendKeys("ecart2@rentacpap.co");
    // 6 | type | id=userpwd | E4syBr34th3
    driver.findElement(By.id("userpwd")).sendKeys("E4syBr34th3");
    // 7 | click | id=button1 | 
    driver.findElement(By.id("button1")).click();
    // 10 | click | linkText=Parts and Accessories | 
    driver.findElement(By.linkText("Parts and Accessories")).click();
    // 11 | click | linkText=Filters | 
    driver.findElement(By.linkText("Filters")).click();
    // 12 | click | linkText=S9 & AirSense 10 Series | 
    driver.findElement(By.linkText("S9 & AirSense 10 Series")).click();
    // 13 | click | css=.buy_now:nth-child(6) | 
    driver.findElement(By.cssSelector(".buy_now:nth-child(6)")).click();
    // 14 | click | id=addtoCart3785 | 
    driver.findElement(By.id("addtoCart3785")).click();
    // 15 | click | linkText=Secure Checkout | 
    driver.findElement(By.linkText("Secure Checkout")).click();
    // 16 | selectFrame | index=3 | 
    driver.switchTo().frame(3);
    // 17 | click | id=credit-card-number | 
    driver.findElement(By.id("credit-card-number")).click();
    // 18 | type | id=credit-card-number | 3700 000000 00002
    driver.findElement(By.id("credit-card-number")).sendKeys("3700 000000 00002");
    // 19 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 20 | selectFrame | index=4 | 
    driver.switchTo().frame(4);
    // 21 | click | id=expiration | 
    driver.findElement(By.id("expiration")).click();
    // 22 | type | id=expiration | 12 / 34
    driver.findElement(By.id("expiration")).sendKeys("12 / 34");
    // 23 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 24 | selectFrame | index=5 | 
    driver.switchTo().frame(5);
    // 25 | click | id=cvv | 
    driver.findElement(By.id("cvv")).click();
    // 26 | type | id=cvv | 2435
    driver.findElement(By.id("cvv")).sendKeys("2435");
    // 27 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 28 | selectFrame | index=6 | 
    driver.switchTo().frame(6);
    // 29 | click | id=postal-code | 
    driver.findElement(By.id("postal-code")).click();
    // 30 | type | id=postal-code | 47568
    driver.findElement(By.id("postal-code")).sendKeys("47568");
    // 31 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 32 | click | id=submit-button | 
    driver.findElement(By.id("submit-button")).click();
    // 33 | click | css=.featherlight-close-icon | 
    driver.findElement(By.cssSelector(".featherlight-close-icon")).click();
    // 36 | click | linkText=Log Out | 
    driver.findElement(By.linkText("Log Out")).click();
  }
}
