// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class QA11Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void qA11() {
    // Test name: QA1_1
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://rentacpap.co/");
    // 2 | setWindowSize | 1575x860 | 
    driver.manage().window().setSize(new Dimension(1575, 860));
    // 3 | click | linkText=Nasal Masks | 
    driver.findElement(By.linkText("Nasal Masks")).click();
    // 4 | click | css=.listProduct:nth-child(2) .buy_now | 
    driver.findElement(By.cssSelector(".listProduct:nth-child(2) .buy_now")).click();
    // 5 | click | id=optionSelect-4793-1 | 
    driver.findElement(By.id("optionSelect-4793-1")).click();
    // 6 | select | id=optionSelect-4793-1 | label=I will send/have sent in my Rx
    {
      WebElement dropdown = driver.findElement(By.id("optionSelect-4793-1"));
      dropdown.findElement(By.xpath("//option[. = 'I will send/have sent in my Rx']")).click();
    }
    // 7 | click | id=optionSelect-4793-1 | 
    driver.findElement(By.id("optionSelect-4793-1")).click();
    // 8 | mouseOver | id=productForm4793 | 
    {
      WebElement element = driver.findElement(By.id("productForm4793"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | mouseOut | id=productForm4793 | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 10 | click | id=optionSelect-4793-2 | 
    driver.findElement(By.id("optionSelect-4793-2")).click();
    // 11 | select | id=optionSelect-4793-2 | label=Standard frame
    {
      WebElement dropdown = driver.findElement(By.id("optionSelect-4793-2"));
      dropdown.findElement(By.xpath("//option[. = 'Standard frame']")).click();
    }
    // 12 | click | id=optionSelect-4793-2 | 
    driver.findElement(By.id("optionSelect-4793-2")).click();
    // 13 | mouseOver | id=persInput-1978[required] | 
    {
      WebElement element = driver.findElement(By.id("persInput-1978[required]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 14 | mouseOut | id=persInput-1978[required] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 15 | click | id=optionSelect-4793-3 | 
    driver.findElement(By.id("optionSelect-4793-3")).click();
    // 16 | select | id=optionSelect-4793-3 | label=3 Included (Small, Medium, Small Wide)
    {
      WebElement dropdown = driver.findElement(By.id("optionSelect-4793-3"));
      dropdown.findElement(By.xpath("//option[. = '3 Included (Small, Medium, Small Wide)']")).click();
    }
    // 17 | click | id=optionSelect-4793-3 | 
    driver.findElement(By.id("optionSelect-4793-3")).click();
    // 18 | click | id=persInput-1978[required] | 
    driver.findElement(By.id("persInput-1978[required]")).click();
    // 19 | select | id=persInput-1978[required] | label=No, thank you.
    {
      WebElement dropdown = driver.findElement(By.id("persInput-1978[required]"));
      dropdown.findElement(By.xpath("//option[. = 'No, thank you.']")).click();
    }
    // 20 | click | id=persInput-1978[required] | 
    driver.findElement(By.id("persInput-1978[required]")).click();
    // 21 | click | id=persInput-1457[required] | 
    driver.findElement(By.id("persInput-1457[required]")).click();
    // 22 | select | id=persInput-1457[required] | label=Yes, add WIDE cushion ($31)
    {
      WebElement dropdown = driver.findElement(By.id("persInput-1457[required]"));
      dropdown.findElement(By.xpath("//option[. = 'Yes, add WIDE cushion ($31)']")).click();
    }
    // 23 | click | id=persInput-1457[required] | 
    driver.findElement(By.id("persInput-1457[required]")).click();
    // 24 | click | id=addtoCart4793 | 
    driver.findElement(By.id("addtoCart4793")).click();
    // 25 | mouseOver | css=.emptyCart > h1 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".emptyCart > h1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 26 | mouseOut | css=.emptyCart > h1 | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 27 | click | linkText=Cleaning and Comfort Products | 
    driver.findElement(By.linkText("Cleaning and Comfort Products")).click();
    // 28 | click | css=.listProduct:nth-child(1) .buy_now | 
    driver.findElement(By.cssSelector(".listProduct:nth-child(1) .buy_now")).click();
    // 29 | click | id=persInput-417[required] | 
    driver.findElement(By.id("persInput-417[required]")).click();
    // 30 | select | id=persInput-417[required] | label=No adapter needed
    {
      WebElement dropdown = driver.findElement(By.id("persInput-417[required]"));
      dropdown.findElement(By.xpath("//option[. = 'No adapter needed']")).click();
    }
    // 31 | click | id=persInput-417[required] | 
    driver.findElement(By.id("persInput-417[required]")).click();
    // 32 | click | id=addtoCart4177 | 
    driver.findElement(By.id("addtoCart4177")).click();
    // 33 | click | linkText=Secure Checkout | 
    driver.findElement(By.linkText("Secure Checkout")).click();
    // 34 | selectFrame | index=3 | 
    driver.switchTo().frame(3);
    // 35 | click | id=credit-card-number | 
    driver.findElement(By.id("credit-card-number")).click();
    // 36 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 37 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 38 | selectFrame | index=4 | 
    driver.switchTo().frame(4);
    // 39 | click | id=expiration | 
    driver.findElement(By.id("expiration")).click();
    // 40 | type | id=expiration | 11 / 223
    driver.findElement(By.id("expiration")).sendKeys("11 / 223");
    // 41 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 42 | selectFrame | index=5 | 
    driver.switchTo().frame(5);
    // 43 | click | id=cvv | 
    driver.findElement(By.id("cvv")).click();
    // 44 | type | id=cvv | 1
    driver.findElement(By.id("cvv")).sendKeys("1");
    // 45 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 46 | selectFrame | index=4 | 
    driver.switchTo().frame(4);
    // 47 | click | id=expiration | 
    driver.findElement(By.id("expiration")).click();
    // 48 | type | id=expiration | 11 / 23
    driver.findElement(By.id("expiration")).sendKeys("11 / 23");
    // 49 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 50 | selectFrame | index=5 | 
    driver.switchTo().frame(5);
    // 51 | click | id=cvv | 
    driver.findElement(By.id("cvv")).click();
    // 52 | type | id=cvv | 1324
    driver.findElement(By.id("cvv")).sendKeys("1324");
    // 53 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 54 | selectFrame | index=6 | 
    driver.switchTo().frame(6);
    // 55 | click | id=postal-code | 
    driver.findElement(By.id("postal-code")).click();
    // 56 | type | id=postal-code | 37485
    driver.findElement(By.id("postal-code")).sendKeys("37485");
    // 57 | selectFrame | relative=parent | 
    driver.switchTo().defaultContent();
    // 58 | click | id=submit-button | 
    driver.findElement(By.id("submit-button")).click();
    // 59 | click | css=.featherlight-close-icon | 
    driver.findElement(By.cssSelector(".featherlight-close-icon")).click();
  }
}
